import java.text.DecimalFormat;
import java.util.Scanner;

/* ======================== *
 *  DO NOT EDIT THIS FILE!  *
 * ======================== */

/**
 * Interactive testing of the ComplexNumber class.
 * @author Mithat Konar
 */
public class ComplexNumberTest {

    /**
     * Print a number on a line with a consistent format.
     * @param n  The number to be printed out
     */
    public static void printFormatted(double n) {
        var df = new DecimalFormat("0.####E0");
        System.out.println(df.format(n));
    }

    /**
     * Interactively test the ComplexNumber class.
     * @param args  Unused
     */
    public static void main(String[] args) {
        var stdin = new Scanner(System.in);
        double real, imag;      // temporary vars to store real and imag parts

        // tests on unary operations
        var num = new ComplexNumber();
        real = stdin.nextDouble();
        imag = stdin.nextDouble();
        num.set(real, imag);

        System.out.print("toString: ");
        System.out.println(num);

        System.out.print("real: ");
        printFormatted(num.getReal());

        System.out.print("imaginary: ");
        printFormatted(num.getImaginary());

        System.out.print("absolute value: ");
        printFormatted(num.abs());

        System.out.println();

        // tests on binary operations
        var other = new ComplexNumber();
        real = stdin.nextDouble();
        imag = stdin.nextDouble();
        other.set(real, imag);

        ComplexNumber result;
        result = num.add(other);
        System.out.print("addition: ");
        System.out.println(result);

        result = num.subtract(other);
        System.out.print("subtraction: ");
        System.out.println(result);

        result = num.mult(other);
        System.out.print("multiplication: ");
        System.out.println(result);

        result = num.div(other);
        System.out.print("division: ");
        System.out.println(result);
    }
}

