import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

// DO NOT EDIT THIS FILE //

/**
 *
 * @author Mithat Konar
 */
public class NeedleHaystack {

    /**
     * @param args  not used
     */
    public static void main(String[] args) {

        Scanner scanner = null;
        var haystack = new ArrayList<String>();   // list of words
        String searchTerm;
                
        // Populate haystack
        try {
            scanner = new Scanner(new FileInputStream("words.txt"));
        } catch (FileNotFoundException e) {
            System.out.println("File does not exist.");
            System.exit(1);
        }
        while (scanner.hasNext()) {
            haystack.add(scanner.next());
        }
        scanner.close();
        
        // Get search term
        scanner = new Scanner(System.in);
        searchTerm = scanner.next();
        scanner.close();        
        searchTerm = searchTerm.toLowerCase();

        // Search for it
        int position = SimpleSearch.search(haystack, searchTerm);
        
        // Report results where first position is 1, not zero. 
        if (position >= 0){
            System.out.printf("\"%s\" is word number %d in the file.%n", 
                    searchTerm, position + 1);
        } else {
            System.out.printf("\"%s\" was not found in the file.%n", 
                    searchTerm);
        }
    }

}
